name: Deploy MultiDocker

on:
  push:
    branches:
      - main # Check your repo's default branch; it might be master!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub (using password-stdin)
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 3: Build client image for testing
      - name: Build React Client Image for Testing
        run: docker build -t rallycoding/react-test -f ./client/Dockerfile.dev ./client

      # Step 4: Run tests on the client
      - name: Run Tests
        run: docker run -e CI=true rallycoding/react-test npm test

      # Step 5: Build multi-container images
      - name: Build Multi Docker Images
        run: |
          docker build -t rallycoding/multi-client ./client
          docker build -t rallycoding/multi-nginx ./nginx
          docker build -t rallycoding/multi-server ./server
          docker build -t rallycoding/multi-worker ./worker

      # Step 6: Push Docker images to Docker Hub
      - name: Push Docker Images
        run: |
          docker push rallycoding/multi-client
          docker push rallycoding/multi-nginx
          docker push rallycoding/multi-server
          docker push rallycoding/multi-worker
