name: Deploy MultiDocker

on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Log in to Docker Hub
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build Docker images
      - run: docker build -t markbilkesh/react-test-up -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true markbilkesh/react-test-up npm test

      - run: docker build -t markbilkesh/multi-client-up ./client
      - run: docker build -t markbilkesh/multi-nginx-up ./nginx
      - run: docker build -t markbilkesh/multi-server-up ./server
      - run: docker build -t markbilkesh/multi-worker-up ./worker

      # Push Docker images to Docker Hub
      - run: docker push markbilkesh/multi-client-up
      - run: docker push markbilkesh/multi-nginx-up
      - run: docker push markbilkesh/multi-server-up
      - run: docker push markbilkesh/multi-worker-up

      # Generate deployment package
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # Deploy to Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env-2
          existing_bucket_name: elasticbeanstalk-ap-south-1-194722446569
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
